# This is a basic workflow to help you get started with Actions

name: .NET Project Automation

on: 
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Create .NET Web API Project
      run: |
        dotnet new webapi -n HelloWorldApi

    - name: Update Program.cs for HelloWorld Endpoint
      run: |
        cd HelloWorldApi
        echo 'var builder = WebApplication.CreateBuilder(args);' > Program.cs
        echo '' >> Program.cs
        echo 'var app = builder.Build();' >> Program.cs
        echo '' >> Program.cs
        echo 'app.MapGet("/hello", () => "Hello World");' >> Program.cs
        echo '' >> Program.cs
        echo 'app.Run();' >> Program.cs
        cd ..

    - name: Build Docker Image
      run: docker build -t hello-world-api .

    - name: Run Docker Container
      run: docker run -d -p 8080:80 hello-world-api

    - name: Test API
      run: |
        sleep 10
        curl http://localhost:8080/HelloWorld
          echo Add other actions to build,
          echo test, and deploy your project.
